# Generated by Django 3.1.1 on 2020-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharactherMarvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characther',
            name='comics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characther',
            name='events',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characther',
            name='series',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characther',
            name='stories',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Comics',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
